version: '3'

services:
  app:
    build:
      context: ./docker/php
#    image: my-laravel-app
    container_name: aeg-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: my-laravel-app
#      SERVICE_TAGS: dev
    working_dir: /var/www/aeg
    volumes:
      - ./:/var/www/aeg
#      - ./docker/mysql:/var/lib/mysql
    depends_on:
      - db
#    command: sh -c "php artisan config:cache && php artisan migrate"
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: aeg-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: aeg
#      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
#      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # Nginx Service
  web:
    image: 'nginx:alpine'
    container_name: aeg-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/aeg
      - ./docker/nginx/vhosts:/etc/nginx/conf.d
    working_dir: /var/www/aeg
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network

volumes:
  dbdata:
    driver: local